name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTRjNmY0NTgtMmNlZi00N2U4LWJmZmQtZTQxNWQzOWY4ZGU0IiwidGVuYW50X2lkIjoiZDA4NzVhOGRkNmI5ZGQ2NGJhZWQ0MGFiNGFiZjUzYjgxNjUwMmU2MjM3OTBiZjFkYjJiYzkwNjA2ZDRkNGJhOSIsImludGVybmFsX3NlY3JldCI6IjIwYzFlNDAyLTI2NGUtNGI1NS04OGM0LTUyY2IwZTQyNGVlNCJ9.W3a56yp07EHu_CiNU_h3tfwA0Pl4DlAwtR839R-74-Y"

JWT_SECRET="HELLO"