import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Intro",
  description: "Generated by create next app by Atharva-3000",
};

export default function RootLayout({
  //name doesn't matter

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <div className="p-4">
          Medium Website
        </div>
        {children}
        </body>
    </html>
  );
}
